### ISSUE TITLE
Doesn't compile with latest flutter on master channel.

### ISSUE THREAD

**Issue by mjaffa-figure** [lukef/qr.flutter#16]
qr_painter.dart

needs this method to await on getting an image back:

Future<ByteData> toImageData(double size,
      {ui.ImageByteFormat format = ui.ImageByteFormat.png}) async {
    final uiImage = await toPicture(size).toImage(size.toInt(), size.toInt());
    return await uiImage.toByteData(format: format);
  }

**Comment by lukef** [comment]
Honestly, I advise you (if possible) to not use master right now. I've logged an issue on the main Flutter tracker (see: https://github.com/flutter/flutter/issues/26655) to see what advice they have on maintaining backwards compatibility because I can't _really_ release a new version and peg it at Flutter master or higher, etc.

I'm also unclear on how stable this change is in terms of the long term release plan of flutter. Will this change reach the stable channel eventually? etc.

Until then, maybe it's best to fork the library and use the fork. If there is enough interest, I'll do another branch.

**Comment by lukef** [comment]
You can now use the dev branch (or tag):

```
dependencies:
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1
```

If there are a lot of changes I'll do a release on pub but using the tag should allow you to pin to a specific version.

If you want to work off the branch, use `ref: 2.0.0-dev` instead.
