### ISSUE TITLE
embeddedImage not working

### ISSUE THREAD

**Issue by mychaelgo** [lukef/qr.flutter#64]
**Describe the bug**
embeddedImage make qr code can't be scanned.

**To Reproduce**
```dart
QrImage(
      data: '7tMKelemz51hL4Z6Q1ug',
      embeddedImage: Image.asset('assets/images/walk_logo_white.png').image,
);
```

**Expected behavior**
User must be able to scan qr code with logo in the center

**Screenshots**
<img width="333" alt="Screen Shot 2019-10-18 at 09 22 45" src="https://user-images.githubusercontent.com/4651658/67062461-8d035780-f18d-11e9-8523-4127c7cf8172.png">
<img width="342" alt="Screen Shot 2019-10-18 at 09 31 07" src="https://user-images.githubusercontent.com/4651658/67062466-8ecd1b00-f18d-11e9-86fb-9a90a4a0654c.png">

**Smartphone (please complete the following information):**
 - Device: iPhone5s Simulator
 - OS: iOS12.2
 - Library version : qr_flutter: ^3.0.1

**Comment by lukef** [comment]
I'm not really sure what you want me to do here. Whether the QR code can be scanned is dependent on the scanner and not the generator. The top QR code could be scanned using the software I tried (Samsung S10 Camera). The bottom one didn't work.

You could try manually setting a higher version # and see if that improves the readability.

**Comment by mychaelgo** [comment]
ok thank you @lukef

**Comment by walterFeng** [comment]
hi, @lukef . I also found the same bug. EmbeddedImage make qr code can't be scanned. this is my code:
```dart
    Container(
      width: widget.pageWidth,
      height: 250,
      alignment: Alignment.center,
      child: QrImage(
        backgroundColor: Colors.white,
        data: "http://www.github.com",
        embeddedImage:
        AssetImage("assets/images/icon_logo_white_bg.png"),
        embeddedImageStyle:
        QrEmbeddedImageStyle(size: Size(20, 20)),
        version: QrVersions.auto,
        size: 250,
      ),
    )
```
when I set `embeddedImageStyle` to `QrEmbeddedImageStyle(size: Size(20, 20))`,this is the result:
![image](https://user-images.githubusercontent.com/23520425/97256246-8520cd80-184d-11eb-967d-be0da8e46776.png)
it is work well.

but, when I set embeddedImage gets bigger, Change `embeddedImageStyle` to `QrEmbeddedImageStyle(size: Size(60, 60))` or remove `embeddedImageStyle` params. The qr code can't be scanned:
![image](https://user-images.githubusercontent.com/23520425/97255532-ce701d80-184b-11eb-8298-45a889849213.png)
not working now.

I think the QR code should change (but it doesn't) when 'embeddedImage' gets bigger, otherwise the logo will overwrite the valid information of the QR code, so that the observable part of the QR code cannot be recognized by the scanner, do you think? Look forward to your reply.

**Comment by mychaelgo** [comment]
@walterFeng have you try to set error correction level =`QrErrorCorrectLevel.H` ?

**Comment by walterFeng** [comment]
> @walterFeng have you try to set error correction level =`QrErrorCorrectLevel.H` ?

@mychaelgo thank you, It is works for me.

but, When the EmbeddedImage-Size exceeds a certain number (e.g. 100), it will still not be able to scan. How do I know the EmbededImage-Size maximum I can assign?

**Comment by mychaelgo** [comment]
is the Embedded Image size cover  > 30% of the Qr Code?

**Comment by walterFeng** [comment]
> is the Embedded Image size cover > 30% of the Qr Code?

got it.  It is works for me when the Embedded Image size cover < 30%. thank you @mychaelgo

**Comment by rehmmann** [comment]
Wrapping QrImage in a container worked for me

```
Container(
              decoration: const BoxDecoration(
                image: DecorationImage(
                    image: AssetImage('assets/images/name.png'),
                    fit: BoxFit.contain),
              ),
              child: QrImage(
     
            )
```

**Comment by NuskySainudeen** [comment]
This code worked for me with **embedded Image**

```
QrImage(
  data: "Hello World",
  size: 180,
  embeddedImage: const AssetImage('assets/images/my_image.png'),
  embeddedImageStyle: QrEmbeddedImageStyle(
  size: const Size(45, 57),
  ),
   gapless: false,
)
```

**Comment by mrclauss** [comment]
If anybody stumbles across this same problem, just like me...:
The trick is **NOT** to specify a size for the embedded image, then its size relative to the QR code always remains the same...
